version: '3'
services:
  chatgpt:
    build:
      context: .
      dockerfile: Dockerfile
    image: chatgpt-flast-api:latest
    container_name: chatgpt-flast-api-container
    restart: always
    ports:
      - "2400:5000"
    environment:
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
      - openai_api_key=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